lexer grammar SchnappiLexer;
LPAR : '(';
RPAR : ')';
COMA : ',';
MAPKW : 'map';
REDUCEKW : 'reduce';
INIT : 'init';
EQJOIN : 'eqjoin';
UNION : 'union';
GENID : 'gId';
EQ : '=';
PLUS : '+' ;
MINUS : '-' ;
STAR : '*';
FSLASH : '/';
ID  : [a-zA-Z][a-zA-Z0-9]* ;
NUM : [1-9][0-9]* ;
WS  : [ \t\r\n]+ -> skip ;