package org.dama.datasynth.runtime.operators

import org.dama.datasynth.executionplan.ExecutionPlan.PropertyGenerator
import org.dama.datasynth.runtime.utils._
import org.dama.datasynth._

/**
  * Created by aprat on 9/04/17.
  */
object InstantiatePropertyGeneratorOperator {

  /**
    * Instantiates a property generator
    * @param info The execution plan node representing the property generator
    * @tparam T The type of the property generated by the instantiated property generator
    * @return The instantiated property generator
    */
  def apply[T](info : PropertyGenerator[T]) : common.PropertyGenerator[T] = {
    var generator = common.PropertyGenerator.getInstance[T](info.className)
    val initParameters : Seq[Any] = info.initParameters.map( x => EvalValueOperator(x))
    generator.initialize(initParameters : _*)
    generator
  }
}
